#!/bin/sh

tag=tg-sns
function_name=tg-sns
zip_file=tg-sns.zip
s3_bucket=distempr-lambda
s3_key=tg-sns/tg-sns.zip

if ! command -v docker >/dev/null; then
  printf >&2 "Docker not installed\n"
  exit 1
fi

if ! command -v aws >/dev/null; then
  printf >&2 "AWS CLI not installed or not on PATH\n"
  exit 1
fi

if ! [ -f Dockerfile ]; then
  printf >&2 "You don't appear to be in the correct directory\n"
  exit 1
fi

docker build -t "$tag" . || exit 1
docker run -v ./build:/mnt "$tag" || exit 1
aws s3 cp "build/$zip_file" "s3://$s3_bucket/$s3_key" || exit 1
aws lambda update-function-code --function-name "$function_name" --s3-bucket "$s3_bucket" --s3-key "$s3_key"
